"""new user columns

Revision ID: 69594d7cd5b9
Revises: 5ee9fed82eaf
Create Date: 2019-03-04 18:00:25.403877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69594d7cd5b9'
down_revision = '5ee9fed82eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
